name = "rewards"
main = "src/index.ts"
compatibility_date = "2025-01-27"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[triggers]
crons = [ "2 0 * * *" ]

[[kv_namespaces]]
binding = "MERKLE_TREES"
id = "a2af0e168ff14aa1bc6e917ad49936ec"

[[kv_namespaces]]
binding = "INCENTIVES_KV"
id = "86e816747a614568ade73194d14aec27"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

